name = "global-pro-automotriz"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "global-pro-db"
database_id = "63359deb-12eb-42cf-ab71-ccd8201fe703"

[vars]
ENVIRONMENT = "production"
